import os
from building import *

cwd = GetCurrentDir()
objs = []

Import('SIFLI_SDK')

# Use the general BLE/BT LCPU patch packaged and built by the SDK.
objs.extend(SConscript(
    os.path.join(SIFLI_SDK, 'example/rom_bin/lcpu_general_ble_img/SConscript'),
    variant_dir='lcpu_patch',
    duplicate=0))

objs.extend(SConscript(
    os.path.join(SIFLI_SDK, 'SConscript'),
    variant_dir='sifli_sdk',
    duplicate=0))

objs.extend(SConscript(
    os.path.join(cwd, '../src/SConscript'),
    variant_dir='src',
    duplicate=0))

Return('objs')

